# Generated by Django 5.2.5 on 2025-09-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_verificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
