# Generated by Django 5.2.5 on 2025-09-15 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_email_verificado_usuario_token_verificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padres',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='padres',
            name='email',
        ),
        migrations.RemoveField(
            model_name='padres',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='padres',
            name='telefono',
        ),
        migrations.AddField(
            model_name='padres',
            name='Usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('padre', 'Padre')], default='padre', max_length=10),
        ),
        migrations.AlterField(
            model_name='padres',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
