# Generated by Django 5.2.5 on 2025-09-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_padres_apellido_remove_padres_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padres',
            old_name='Usuario',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='padres',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='padres',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padres',
            name='fecha_formulario',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
