# Generated by Django 5.2.5 on 2025-09-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_usuario_padres_usuario_padres_aprobado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padres',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
