# Generated by Django 5.2.6 on 2025-09-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_padres_fecha_expiracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padres',
            old_name='fecha_formulario',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='padres',
            name='fecha_expiracion',
        ),
    ]
