"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os   # Importa el módulo os para manejar variables de entorno
from dotenv import load_dotenv

# Carga las variables de entorno desde el archivo .env
load_dotenv(os.path.join(os.path.dirname(__file__), '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables de entorno desde el archivo .env en la raíz del proyecto
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(=r+b2kjt27a&!-zx43ohf_=v)lmiijfu!l2_ptjhac&q@va-0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ============================================================================
# CONFIGURACIÓN DE APLICACIONES
# ============================================================================

INSTALLED_APPS = [
    # Aplicaciones por defecto de Django
    'django.contrib.admin',           # Panel de administración web
    'django.contrib.auth',            # Sistema de autenticación
    'django.contrib.contenttypes',    # Framework para tipos de contenido
    'django.contrib.sessions',        # Framework para sesiones
    'django.contrib.messages',        # Framework para mensajes
    'django.contrib.staticfiles',     # Framework para archivos estáticos

    # Aplicaciones de terceros
    'rest_framework',                 # Framework para APIs REST
    'rest_framework.authtoken',       # Sistema de tokens de autenticación
    # Manejo de CORS (Cross-Origin Resource Sharing)
    'corsheaders',

    # Aplicaciones locales
    'api',                           # Nuestra aplicación principal
]

# ============================================================================
# CONFIGURACIÓN DE MIDDLEWARE
# ============================================================================

MIDDLEWARE = [
    # Maneja CORS (debe ir primero)
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',  # Seguridad
    'django.contrib.sessions.middleware.SessionMiddleware',  # Sesiones
    'django.middleware.common.CommonMiddleware',    # Funcionalidad común
    'django.middleware.csrf.CsrfViewMiddleware',     # Protección CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Autenticación
    'django.contrib.messages.middleware.MessageMiddleware',  # Mensajes
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Protección clickjacking
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# ============================================================================
# CONFIGURACIÓN DE BASE DE DATOS
# ============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'mssql',            # Motor de base de datos: SQL Server
        'NAME': os.getenv('DB_NAME'),    # Nombre de la base de datos
        'USER': os.getenv('DB_USER'),     # Usuario de la base de datos
        # Contraseña de la base de datos
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),           # Servidor de la base de datos
        'PORT': '',                   # Puerto (vacío = puerto por defecto)
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Driver ODBC para SQL Server
        },
    }
}


# ============================================================================
# VALIDACIÓN DE CONTRASEÑAS
# ============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================================
# CONFIGURACIÓN INTERNACIONAL
# ============================================================================

LANGUAGE_CODE = 'en-us'  # Idioma por defecto
TIME_ZONE = 'UTC'        # Zona horaria
USE_I18N = True          # Internacionalización
USE_TZ = True            # Soporte para zonas horarias


# ============================================================================
# ARCHIVOS ESTÁTICOS
# ============================================================================

STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# MODELO DE USUARIO PERSONALIZADO
# ============================================================================

# Especifica que usamos nuestro modelo de usuario personalizado
AUTH_USER_MODEL = 'api.Usuario'

# ============================================================================
# CONFIGURACIÓN DE CORS (Cross-Origin Resource Sharing)
# ============================================================================

# Orígenes permitidos para peticiones CORS (desde el frontend)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Servidor de desarrollo de Vite (React)
    "http://127.0.0.1:5173",  # Alternativa para localhost
]

# Para desarrollo, también permitir todos los orígenes (TEMPORAL)
CORS_ALLOW_ALL_ORIGINS = True

# Permite el envío de cookies y headers de autenticación
CORS_ALLOW_CREDENTIALS = True

# Headers permitidos en las peticiones CORS
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Métodos HTTP permitidos
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ============================================================================
# CONFIGURACIÓN DE DJANGO REST FRAMEWORK
# ============================================================================

REST_FRAMEWORK = {
    # Clases de autenticacion por defecto
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],

    # Permisos por defecto para todas las vistas
    'DEFAULT_PERMISSION_CLASSES': [
        # Permite acceso sin autenticación por defecto
        'rest_framework.permissions.AllowAny',
    ],

    # Renderizadores por defecto (formato de respuesta)
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # Respuestas en formato JSON
    ],
}

# ============================================================================
# CONFIGURACIÓN DE EMAIL (GMAIL)
# ============================================================================

# Configuración para enviar emails desde Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Servidor SMTP de Gmail
EMAIL_PORT = 587  # Puerto para TLS
EMAIL_USE_TLS = True  # Usar TLS para seguridad
EMAIL_HOST_USER = 'livecoding0910@gmail.com'  # Tu email de Gmail
EMAIL_HOST_PASSWORD = 'aixr qssh ijtz vlhf'  # Contraseña de aplicación de Gmail

# Configuración adicional
EMAIL_USE_SSL = False  # No usar SSL (usamos TLS)
# Email desde el cual se envían los correos
DEFAULT_FROM_EMAIL = 'livecoding0910@gmail.com'
